### ISSUE TITLE
Unable to install update 0.2.7

### ISSUE THREAD

**Issue by TheRarita** [Stendarpaval/mob-attack-tool#19]
When trying to update to 0.2.7 the updater fails. Tried to uninstall the mod completely and enter the manifest URL manually (https://raw.githubusercontent.com/Stendarpaval/mob-attack-tool/main/module.json) but still fails to instal 
Error "Installation failed: Not found"

**Comment by Stendarpaval** [comment]
Thanks for the heads-up, I was experimenting with a different method of zipping the module. Seems like the experiment failed. I'll quickly publish a new release which uses the old method.

**Comment by Stendarpaval** [comment]
Alright, [v0.2.8](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/v0.2.8) is out which should fix this problem. I tested it and was able to properly update to v0.2.8. Please try to update or reinstall the module to get a working version of Mob Attack Tool. Let me know if it works :)

**Comment by TheRarita** [comment]
Seems to be working just fine now :)

**Comment by Stendarpaval** [comment]
That's good to hear! I've worked out the problem on my end. From [v0.2.10](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.10) onwards, this won't happen again. I'll go ahead and close this issue, but feel free to reopen it if problems reoccur for some reason. :)
