### ISSUE TITLE
Error Message: Select a target with a valid ac value!

### ISSUE THREAD

**Issue by jhutc82** [Stendarpaval/mob-attack-tool#20]
Hello,

I can't seem to get Mob Attack Tool to work. I get an error message ("Select a target with a valid ac value!") on any actor whether I create one from scratch or use them from a compendium. I am using Foundry version 0.7.10 with DnD5e Fifth Edition System 1.2.4.

I have disabled all active modules and only enabled Mob Attack Tool and continue to receive this error.

Please see the below images:

Error Message:
![image](https://user-images.githubusercontent.com/43892492/121134444-046d7b00-c7f9-11eb-8107-9436e180d060.png)

Example Actor:
![image](https://user-images.githubusercontent.com/43892492/121134748-61693100-c7f9-11eb-8e9a-eaa4db7a1886.png)

I have checked the attributes.ac.value variable and it does seem populated:
![image](https://user-images.githubusercontent.com/43892492/121135177-dd637900-c7f9-11eb-8cd7-3754aec7df71.png)

Thank you,

Justin

**Comment by Stendarpaval** [comment]
This is intended behavior when you have the "Use mob rules or roll individually" setting set to "Mob Rules" (which is the default). It's not really an error message, but a warning that you haven't targeted a token yet. 

What it means is that you need to not only select the tokens of your mob, but you also need to target the token that the mob will attack. You can target a token by right clicking it to bring up the token HUD, and then clicking the button I circled in red here:

<img width="756" alt="mat-target-example" src="https://user-images.githubusercontent.com/17188192/121149660-24c22780-c843-11eb-961b-01e2915f3c23.png">

You can tell that you successfully targeted a token when four orange arrows appear around it, as shown below:

<img width="756" alt="mat-target-example-2" src="https://user-images.githubusercontent.com/17188192/121149793-402d3280-c843-11eb-8cae-053b1eb556a7.png">

I hope that clears up any confusion. As a matter of fact, one of the next major features I plan on adding to Mob Attack Tool is allowing multiple targets to be selected, for which I'll update the interface to make targeting easier in general. 

For now, though, I recommend installing the [Easy Target](https://foundryvtt.com/packages/easy-target) module, which allows you to target tokens with Alt + Click.

**Comment by jhutc82** [comment]
This does clear it up! My apologies for my misunderstanding and I appreciate you taking the time to explain it to me!

Thanks again, 

Justin
