### ISSUE TITLE
Manual AC modifier

### ISSUE THREAD

**Issue by benbarbour** [Stendarpaval/mob-attack-tool#21]
For those of us that don't use much automation it would be nice if this tool had an option to manually enter an AC modifier for the target. For me the "Shield" spell is just an icon.

**Comment by Stendarpaval** [comment]
Interesting idea, I can imagine how that would be useful. I'll work on an implementation for this as part of some refactoring of the Mob Attack Dialog handlebars template.

**Comment by Stendarpaval** [comment]
I have added a manual AC modifier feature in release [v0.2.12](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.12). It is accompanied by a setting which controls whether or not the modifier persists between uses of Mob Attack Tool. Please let me know if you run into any bugs after updating :)

**Comment by benbarbour** [comment]
Looks good! I personally might want it on the first tab, because I think I'll be using it a lot with my players' abilities. However, the separation of attackers and targets on different tabs is logical, especially if you're going to add more to the targets tab later on.

**Comment by Stendarpaval** [comment]
Alright, in that case I'll close this issue. If related issues pop up, feel free to reopen it :)
