### ISSUE TITLE
Option to show results to players

### ISSUE THREAD

**Issue by benbarbour** [Stendarpaval/mob-attack-tool#22]
The results from Mob Attack Tool are always whispered to me, the GM, but I generally roll in the open. Could it be optional to send the result card to everyone, or maybe make it depend on the current roll mode?

**Comment by Stendarpaval** [comment]
I've been meaning to add a setting for this, but I kept forgetting to do so. 😅 I'll make sure to do so in an upcoming release.

**Comment by Stendarpaval** [comment]
I've remembered to add this feature in release [v0.2.12](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.12). If you enable the "Stop whispering Mob Attack results" setting in the Rolls tab of Mob Attack Tool's Advanced Settings, then the results message should obey roll mode in terms of who can see them. Please let me know if you run into any bugs related to this after installing the new release :)

**Comment by benbarbour** [comment]
Just running a few small tests, but looks great so far! Thanks! :D

**Comment by Stendarpaval** [comment]
Since the requested feature was added, I'll go ahead and close this issue.
