### ISSUE TITLE
Persist "Skip turns" setting / default "Skip turns" setting

### ISSUE THREAD

**Issue by benbarbour** [Stendarpaval/mob-attack-tool#23]
Could there be a global setting to check the "Skip next turn" button by default? Or maybe just have it remember what was used for the last mob attack?

**Comment by Stendarpaval** [comment]
Either is possible, though the latter seems more user-friendly. Shouldn't be too hard to include in an upcoming release.

**Comment by Stendarpaval** [comment]
This feature was added in release [v0.2.14](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.14) (well, technically already in [v0.2.13](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.13), but that version still had  a bug I missed. 

Let me know if it works as you'd expect after updating :)

**Comment by Stendarpaval** [comment]
I'll go ahead and close this issue. Feel free to reopen it if you encounter any bugs related to this :)
