### ISSUE TITLE
Initiative groups

### ISSUE THREAD

**Issue by benbarbour** [Stendarpaval/mob-attack-tool#24]
Hi. I know I'm filing a lot, but only because I think this is great and I'm going to be using it regardless of if/when these issues are fixed! :)

Anyways, I know you mention the Group Initiative module, but I'm not sure it's being maintained anymore. It's not updated for 0.8.6 anyway. So I'm wondering if you would consider implementing it's features as part of this module (or maybe I'll take a stab it if you're interested)? Even if it gets an update, I think one of the main advantages of this module is to speed up combat, and it really does that best with grouped initiative. Another feature that could be added as part of that would be to automatically select (or have a button to select) all the tokens with an identical type and initiative score when the first one in the group takes it's turn.

**Comment by Stendarpaval** [comment]
I'm just glad that they were mostly feature requests. For a second I though there must have been some kind of bug I missed and I hadn't checked for a few days :P.

Interesting that you bring up [Group Initiative](https://github.com/tonifisler/foundry-group-initiative). I noticed that their current release didn't function yet, but the last commit to their repo (from 15 days ago) suggested that it fixed the compatibility issues. So I downloaded the repo as a ZIP-file, unzipped it and placed the required files and folders in the appropriately named `group-initiative` directory in the `modules` folder of the userdata path of my Foundry installation. And then it worked! So their code is up to date, but they seem not to have released it yet. 

If my experiment above didn't work out, then I might've made plans to implement a similar feature for Mob Attack Tool. I'm not sure whether or not that's the best course of action now. Perhaps making an issue about it could help. 

As for automatic selection of tokens, that is actually what the "Save Mob" and "Load Mob" features are building towards. They currently only swap out the monster and weapon data, but eventually they'll also select the tokens (if they're on the current scene) of that mob. I plan to add "Next" and "Previous" buttons to make it easier to cycle between mobs. 

Even if the Group Initiative feature isn't added to Mob Attack Tool, I'm still interested in a feature that makes Mob Attack Tool automatically select the correct mob when it's their turn in combat. Might be possible with a single button in the Mob Attack Dialog. 

This will take a while to hammer out, though. And like I wrote in issue #21, higher up on the task list is refactoring the Mob Attack Dialog. I was originally planning to work on selecting multiple targets after that, but I think I'll work on mob token selection first. Probably the multiple target feature after that, followed by features involving the combat tracker.

**Comment by benbarbour** [comment]
For anyone else wanting something like this while the module is not yet officially updated, I created this macro:

```
async function addMobs(tokens) {
  for (t of tokens) {
    if (!token.inCombat) await token.toggleCombat();
  }
  
  const combatants = tokens.map(t => game.combat.getCombatantByToken(t.id));
  await game.combat.rollInitiative(combatants[0].id);
  game.combat.turns.filter(c => c.id !== combatants[0].id).forEach(
    c => game.combat.setInitiative(c.id, combatants[0].initiative)
  );

  if (!combat.started) {
    await game.combat.startCombat();
  }
}

addMobs(canvas.tokens.controlled);
```

Select tokens, run the macro, and it will add them to combat, roll initiative once for one of them and set all the others to the same value, then start the combat. I might just keep using this actually, as it's a nice way to divide groups up if I don't want all 50 zombies going at once... I can select groups of 8 or so and give the groups their own initiative.

**Comment by benbarbour** [comment]
For anyone wanting an alternative to the Group Initiative module, I'm using this macro:

```
async function addMobs(tokens) {
  if (tokens.length < 1) {
   	ui.notifications.info('No tokens selected!');
    return;
  }
  
  for (t of tokens) {
    if (!token.inCombat) await token.toggleCombat();
  }
  
  const combatants = tokens.map(t => game.combat.getCombatantByToken(t.id));
  const combatantIds = combatants.map(c => c.id).filter(id => id != combatants[0].id);
  const combat = await game.combat.rollInitiative(combatants[0].id);
  combat.turns.filter(c => combatantIds.includes(c.id)).forEach(
    c => combat.setInitiative(c.id, combatants[0].initiative)
  );
  debugger;

  if (!combat.started) {
    await combat.startCombat();
  }
}

addMobs(canvas.tokens.controlled);
```

Select tokens, run the macro, and they'll all be added to the current combat at the same initiative. If they're already in combat their initiative will be re-rolled. If they are different actors then the initiative formula of the first selected one will be used for all of them.

**Comment by Stendarpaval** [comment]
Bit of an update on this issue: release [v0.2.22](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.22) brings Grouped Initiative functionality as well as an initial mob focused feature, namely the grouping of mob initiatives. 

I'll tackle automatic mob token selection in a future release, since it's kinda late and I'll want to investigate whether or not my go-to solution to that problem interferes with CUB's token selection feature.

**Comment by Stendarpaval** [comment]
So, release [v0.2.24](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.24) includes the automatic token selection feature. It'd help me out if you could update and let me know if you run into any related bugs with it :)

**Comment by Stendarpaval** [comment]
Presuming no bugs were encountered, I'll go ahead and close this issue for now.
