### ISSUE TITLE
Latest release has broken manifest URL

### ISSUE THREAD

**Issue by Norc** [Stendarpaval/mob-attack-tool#25]
Links to https://github.com/Stendarpaval/mob-attack-tool/releases/download/0.2.11/module.jsonhttps://github.com/Stendarpaval/mob-attack-tool/releases/download/0.2.12/module.json

**Comment by Stendarpaval** [comment]
Wow, thanks for the heads-up! I must have messed up updating the manifest link. I fixed it just now.

**Comment by Stendarpaval** [comment]
Since this seems fixed, I'll go ahead and close this issue. Feel free to reopen it if related problems do pop up again.
