### ISSUE TITLE
Module doesnt initiate attacks

### ISSUE THREAD

**Issue by mesoraven** [Stendarpaval/mob-attack-tool#30]
First of all EXCELLENT module, im really glad someone automated this.

so module was working fine then i tried to change the setting to do individual attacks, to see what it was like. since that point the module wont initiate the attacks when i click the button.

the console throws up the following

Mob Attack Tool | Executed Mob Attack
utils.js:317 Uncaught (in promise) TypeError: Cannot read property 'checked' of undefined
    at prepareMobAttack (utils.js:317)
    at HTMLButtonElement.<anonymous> (mobAttackTool.js:764)
    at HTMLFormElement.dispatch (jquery.min.js:2)
    at HTMLFormElement.v.handle (jquery.min.js:2)
prepareMobAttack @ utils.js:317
(anonymous) @ mobAttackTool.js:764
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
async function (async)
(anonymous) @ mobAttackTool.js:764
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

other than that nothing happens

**Comment by Stendarpaval** [comment]
Glad to hear you like it, and thanks for reporting this bug!

> so module was working fine then i tried to change the setting to do individual attacks

Just to make sure I understand, do you mean that you changed "Mob Rules" to "Individual Attack Rolls" in the settings? 

Also, could you check if the problem goes away if you enable the "Include option to end grouped mob turns" setting, circled in red below?

<img width="500" alt="MAT-include-end-mob-turn" src="https://user-images.githubusercontent.com/17188192/124330687-3f5f9600-db8e-11eb-9cc4-691bd9d67fbd.png">

I actually noticed just now that disabling that setting causes similar error messages when showing or hiding the collapsible options, but I'd like to know if it's related to the bug you're experiencing. 

In any case I'll work on fixing that bug on Sunday at the earliest :)

**Comment by mesoraven** [comment]
"Just to make sure I understand, do you mean that you changed "Mob Rules" to "Individual Attack Rolls" in the settings?"

Yep that setting, however see below

"Also, could you check if the problem goes away if you enable the "Include option to end grouped mob turns" setting, circled in red below?"

Just re enabled it and yep its working again. i thought that that auto ending the turns didnt realise it it completed the attacks. awesome thanks man!

**Comment by Stendarpaval** [comment]
With the release of [v0.2.22](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.22), this bug should be squashed. 

Could you update and tell me whether or not you still run into that bug (if you disable the "Include option to end grouped mob turns" setting again)? That'd help me out a lot :)

**Comment by Stendarpaval** [comment]
I'll go ahead and close this issue for now, feel free to reopen it if you run into any bugs related to this :)
