### ISSUE TITLE
It skips the next mob group that hasn't attacked yet

### ISSUE THREAD

**Issue by jocolamarco** [Stendarpaval/mob-attack-tool#31]
v 0.2.23

Multiple tokens with same name but belonging to different saved mobs.
after i mob attack with the first group it skips also the next mob group whereas i expected it to only skip this group:

![image](https://user-images.githubusercontent.com/45291719/125178676-04d5a900-e1df-11eb-87f8-e47a7107bd79.png)

**Comment by Stendarpaval** [comment]
Thanks for reporting this bug! I forgot to implement some kind of check for saved mobs in the "skip turns" feature, logically it should work as you assumed. I'll take a crack at fixing this bug tomorrow, shouldn't be too complicated. :)

**Comment by Stendarpaval** [comment]
I fixed this bug in the newly released [v0.2.24](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.24). Could you update and let me know if the fix works for you? That'd be great :)

**Comment by jocolamarco** [comment]
> 
> 
> I fixed this bug in the newly released [v0.2.24](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.2.24). Could you update and let me know if the fix works for you? That'd be great :)

Will check. Are mobs lost when updating or need to be re-created for it to be effective?

**Comment by jocolamarco** [comment]
confirm fixed on new version

**Comment by Stendarpaval** [comment]
> Are mobs lost when updating or need to be re-created for it to be effective?

Saved mobs should persist between updates. 

> confirm fixed on new version

Thanks for confirming that the bug is fixed! :D
