### ISSUE TITLE
Clarify in the UI that the mob must be first saved to skip mob initiative.

### ISSUE THREAD

**Issue by caewok** [Stendarpaval/mob-attack-tool#32]
**Setup**
Foundry 0.8.8, dnd5e 1.3.6, Mob Attack 0.3.1. 

**Issue**
When I first tried to use this, I selected "Skip turns of next mob combatants", but no one was skipped. I finally figured out that unless a mob is first saved, it will not skip. My (naive) expectation was that once the mob attack was rolled, the initiative tracker would be forwarded past the mob combatants, at least if they were all grouped together in the initiative. 

**Proposed Solution**
Some note in the settings or in the pop-up that would give users a hint that they need to save mob combatants for this functionality to work. 

Thanks, and love all that you have done with this module!

**Comment by Stendarpaval** [comment]
While it should indeed skip saved mobs, the "skip mob turns" feature *should* also skip the turns of selected tokens as long as they are grouped together and include the current combatant. 

So this seems like a bug of some kind! Or perhaps I overlooked a possible use case. I'll investigate. Can you confirm whether or not you had the tokens selected when executing a mob attack? And if so, was one of the selected tokens the current combatant in the combat tracker?

**Comment by Stendarpaval** [comment]
I actually already found the source of the bug and fixed it. I'll move on to your other issue and see if I can fix both in a single release. :)

**Comment by Stendarpaval** [comment]
[v0.3.2](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.2) should include a fix for this! Please let me know if it works for you, so we can close this issue ;)

**Comment by caewok** [comment]
Yes, this worked. Thanks!
