### ISSUE TITLE
Conflict with CUB's re-roll initiative setting

### ISSUE THREAD

**Issue by caewok** [Stendarpaval/mob-attack-tool#33]
**Setup**
Foundry 0.8.8, dnd5e 1.3.6, Mob Attack 0.3.1, Combat Utility Belt (CUB) 1.6.0

**Issue**
When CUB's setting "Enable Reroll Initiative" is set, it appears to mess up Mob Attack's Grouped Initiative rolls for subsequent rounds. That setting automatically re-rolls initiative at the start of every turn after the first, and it seems that Mob Attack is not picking up on that fact. Thus grouped combatants are no longer sharing the same initiative after the first turn.

Obviously, I can disable this setting for now. It does tend to be a bit of a timesaver, so it is nice to have if you want new initiatives each round. Thanks!

**Comment by Stendarpaval** [comment]
Sure, I'll see if there's a way to hook into CUB's reroll method. :)

**Comment by Stendarpaval** [comment]
So, [v0.3.2](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.2) *does* technically add support for this, but it currently comes at a price: CUB's combat tracker related methods for Enhanced Conditions and Pan / Select won't function while the "Group Initiative for CUB's Reroll Initiative" setting is turned on.

I've made a quick [PR](https://github.com/death-save/combat-utility-belt/pull/576) over at CUB's repository that would fix this, but it's a quick and dirty solution. I know of a more proper one, but it will probably require me to use libWrapper and I'm not sure I want to spend time to learn how that works right now. While it might seem more "proper", it's also much more complicated. 🤔 

Knowing myself, I might actually start looking into it now that I have a genuine reason to do so. Either way, please let me know if the current solution of v0.3.2 works for you without bugs. :)

**Comment by caewok** [comment]
I can strongly recommend libWrapper. Does take some time to figure out, but it is worth it. FYI, my [libRuler](https://github.com/caewok/fvtt-lib-ruler) and [elevation ruler](https://github.com/caewok/fvtt-elevation-ruler/blob/master/scripts/patching.js) modules use libWrapper extensively, if you are looking for examples. (Look specifically at the patching.js file in the scripts folder for each.)

Right now, v0.3.2 does not quite work properly with the re-roll initiative. Same as before, grouped combatants are no longer sharing the same initiative after the first turn if re-roll is on.

**Comment by Stendarpaval** [comment]
Thanks for the recommendation, I'll check those out!

> Right now, v0.3.2 does not quite work properly with the re-roll initiative. Same as before, grouped combatants are no longer sharing the same initiative after the first turn if re-roll is on.

Strange. Are you sure you enabled the "Group Initiative for CUB's Reroll Initiative" setting in Mob Attack Tool's Advanced Settings? 

If it is, I don't know why it's not working. Though perhaps the next version using libWrapper might solve this.

**Comment by caewok** [comment]
Okay, thanks, that was it. I found the "Group Initiative for CUB's Reroll Initiative" and with it enabled, it works!

**Comment by Stendarpaval** [comment]
In [v0.3.4](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.4) I included a libWrapper based fix that should make Reroll Initiative play nice with Group Initiative without compromising any other functionality of CUB.
