### ISSUE TITLE
Arrow buttons not working in the pop-up

### ISSUE THREAD

**Issue by caewok** [Stendarpaval/mob-attack-tool#34]
**Setup**
Foundry 0.8.8, dnd5e 1.3.6, Mob Attack 0.3.2

**Issue**
In the pop-up dialog to set the Mob Attack, the up/down arrows for the number boxes do not work. (They do nothing.) Entering numbers manually does work.

**Console Error**
The console displays this error:

> Uncaught (in promise) TypeError: numAttack.isNaN is not a function
>     activateListeners https://vtt.planeteternium.com/modules/mob-attack-tool/scripts/mobAttackTool.js:398
>     jQuery 8
>     activateListeners https://vtt.planeteternium.com/modules/mob-attack-tool/scripts/mobAttackTool.js:376
>     _render https://vtt.planeteternium.com/scripts/foundry.js:2070
>     _render https://vtt.planeteternium.com/scripts/foundry.js:2729
>     render https://vtt.planeteternium.com/scripts/foundry.js:2004
>     mobAttackTool https://vtt.planeteternium.com/modules/mob-attack-tool/scripts/mobAttackTool.js:42
>     onClick https://vtt.planeteternium.com/modules/mob-attack-tool/scripts/mobAttackTool.js:16
>     _onClickTool https://vtt.planeteternium.com/scripts/foundry.js:27425
>     jQuery 9
>     activateListeners https://vtt.planeteternium.com/scripts/foundry.js:27381
>     _render https://vtt.planeteternium.com/scripts/foundry.js:2070
>     render https://vtt.planeteternium.com/scripts/foundry.js:2004
>     _onClickTool https://vtt.planeteternium.com/scripts/foundry.js:27435
>     jQuery 9
>     activateListeners https://vtt.planeteternium.com/scripts/foundry.js:27381
>     _render https://vtt.planeteternium.com/scripts/foundry.js:2070
>     render https://vtt.planeteternium.com/scripts/foundry.js:2004
>     _onClickTool https://vtt.planeteternium.com/scripts/foundry.js:27435
>     jQuery 2
> mobAttackTool.js:398:18

**Possible solution**
In the file `mobAttackTool.js`, consider changing `numAttack.isNaN()` to `Number.isNaN(numAttack)`. (See, e.g., [this description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) as to why.)

This may be more treating the symptom than a solution, however, because I would have thought that numAttack would be a number already. This may be caused by a different bug as well, but switching the Number.isNaN will still probably help in edge cases, and avoids throwing an error.

Thanks!

**Comment by Stendarpaval** [comment]
Huh, how curious. I forgot to test that function, and can indeed replicate this bug. Very strange, though. `Number.isNaN(numAttack)` does fix it, but yes numAttack is the result of a `parseInt()` so it should be a number, or be `undefined` if something in there went wrong. 

I'll look into it, might push a small patch soon too. Thanks for the report!

**Comment by Stendarpaval** [comment]
This bug should be fixed as of the newly released [v0.3.3](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.3). Please let me know if the fix works for you, so we can close this issue too :)

**Comment by caewok** [comment]
Fixed. Thanks!
