### ISSUE TITLE
On use Macro not firing, when attack misses

### ISSUE THREAD

**Issue by Scharage** [Stendarpaval/mob-attack-tool#43]
As in the title: When activating the on use macro for the tool, it will only fire when an attack hits. Shouldn't it be used regardless?

**Comment by Stendarpaval** [comment]
Hmm, back when this feature was requested (in issue #26), the main use case was for executing JB2A macros for weapon and spell animations. These should of course only be triggered by attacks that hit, and for the sake of convenience I built that functionality into the feature. 

I don't mind adding a setting to choose whether or not to trigger on use macros based on hit attacks, though. Can you tell me what kind of macros you'd use if such a setting existed? That way I can test if it works as intended.

**Comment by Scharage** [comment]
I also would use it for weapon and spell animation, but an animation that literally misses the target, as this is possible to do with Sequencer. If you want i can code you a macro which uses the logic.

**Comment by Scharage** [comment]
Here is the macro for a firebolt
```
// Get all targets with "advanced macro"
const targets= args[0].targets;
//Get all controlled tokens
const controlledList = canvas.tokens.controlled;
//Check if one token is selected and another is targeted
if(targets.length === 0 || controlledList.length === 0){
  return;
}
//The x controlled token attacks the x mod y chosen target
const controlledTokenIdList = controlledList.map(x=> x.data._id);
const attackIndex = controlledTokenIdList.indexOf(args[0].tokenId) % targets.length;
//Do animation
new Sequence()
  .effect()
    .file("jb2a.fire_bolt.orange")
    .atLocation(args[0].tokenId)
    .reachTowards(args[0].targets[attackIndex])
    .JB2A()
    .missed(args[0].hitTargets.length === 0)
  .play();
```
Midi-qol, Advanced Macro, Sequencer and JB2A needed.

**Comment by Stendarpaval** [comment]
Thank you, I'll pick this up for the next release :)
