### ISSUE TITLE
Incompatible with new Group Initiative module

### ISSUE THREAD

**Issue by Hydrall** [Stendarpaval/mob-attack-tool#46]
When using the new [Group Initiative](https://github.com/vtt-lair/foundry-group-initiative) module, creatures are no longer grouped and roll separate initiatives, provided that Mob Attack Tool is enabled.

Presumably something related to the old Grouped Initative module?

![image](https://user-images.githubusercontent.com/14931056/141199723-5dfa3320-c6fe-4572-bfd6-13f64cb66fd8.png)

**Comment by Stendarpaval** [comment]
Did you turn off the "Enable Group Initiative" setting in the Module tab of Mob Attack Tool's Advanced Settings? That should fix this, I think. If it doesn't, then I have a pretty good idea how to fix that in a new release.

Or do you want to continue using Mob Attack Tool's "Mob Initiative" setting, which also groups the initiative of saved mobs? In that case, I'm afraid you'll have to deactivate the new Group Initiative module. If you're still looking for a way to collapse initiative groups, then you could keep an eye out for the Combat Tracker Groups (CTG) module, which arcanist is developing right now.

**Comment by Stendarpaval** [comment]
The newly released [v0.3.13](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.13) should fix this issue. I'll go ahead and close it, but feel free to reopen it if you're still encountering this problem with the new release.
