### ISSUE TITLE
[Bug] When used in Foundry v9, disables encounter rolling

### ISSUE THREAD

**Issue by NateHawk85** [Stendarpaval/mob-attack-tool#48]
Foundry build: v9 build 238
DnD5e system version: 1.5.6
Modules installed: Mob Attack Tool, Found the Culprit
Settings: Defaults
Issue: When clicking on either the "dice" or "Roll All" buttons in the Combat Tracker, either before or after beginning combat... The dice roll, yet the Actor's initiative does not update accordingly. 
Steps to reproduce
1) Enable a fresh install of Mob Attack Tool
2) Add an NPC or Player Character to the combat tracker
3) Click the "Roll Initiative" button for that character. Alternatively, click the "Roll All" button in the top right
![image](https://user-images.githubusercontent.com/7596412/147139899-1c6182ce-a973-437e-8ef1-cac280734697.png)
Expected outcome: Actor initiatives update with the rolled value
Actual outcome: Actor initiatives remain the exact same as if the initiative values were not rolled
![image](https://user-images.githubusercontent.com/7596412/147139930-003016c2-a802-491b-bf04-47f59f5a51ae.png)

![image](https://user-images.githubusercontent.com/7596412/147140010-e4adce28-f080-41a6-8556-82a896c82557.png)

**Comment by ABrandau** [comment]
I can confirm i am having the same issue.

**Comment by Stendarpaval** [comment]
Thank you for reporting this, I was able to reproduce it as well. 

Fixing this will be my top priority for making Mob Attack Tool compatible with V9.

**Comment by Stendarpaval** [comment]
As you can read in [v0.3.13's release notes](https://github.com/Stendarpaval/mob-attack-tool/releases/tag/0.3.13), the initiative rolling issue should be fixed. Let me know if you still run into similar issues, otherwise this one can be closed. :)

**Comment by NateHawk85** [comment]
I'll take a look at this as soon as I get the chance. Thank you, as always, for being so quick on the updates!
