### ISSUE TITLE
Mob attack tool (might) mess up the combat encounter

### ISSUE THREAD

**Issue by mike-marshall0164** [Stendarpaval/mob-attack-tool#51]
I'm updating from 7.10 to 9 and going through modules 1 by 1. Mob attack seems to be causing issues with rolling initiative.

I'm also using the grouped initiative module, but without mob attack it works as expected. Without grouped init and only mob attack it seems to not want to register initiative rolls. I peeped the console output and no errors.

**Comment by Stendarpaval** [comment]
Could you try uninstalling Mob Attack Tool and then reinstalling it, while making sure the new version is 0.3.13? Please try this even if Foundry already says that Mob Attack Tool is version 0.3.13 and fully up to date.

I'm fairly sure that reinstalling the module this way will solve your issue. I had to do this myself as well.

**Comment by ctbritt** [comment]
uninstalling and reinstalling fixed it for me!

**Comment by Biglulux** [comment]
Also had this issue with 0.3.13 and Foundry v9 build 238 - initiative would not show up in the combat tracker. Reinstalling the module fixed it.

**Comment by mike-marshall0164** [comment]
Not sure if it was your update or the reinstall but this worked for me! Thanks!
